/**
 * Sudoku puzzle generator.
 *
 * A valid full solution is generated by randomized backtracking, then cells
 * are removed one by one (in random order, over several passes) while the
 * puzzle keeps a unique solution, until the difficulty's target clue count
 * is reached. Removals that would create multiple solutions are rolled back.
 *
 * Two entry points exist: generateSudoku() uses Math.random() for a fresh
 * random puzzle every call, while generateSudokuSeeded() derives a
 * deterministic PRNG from a seed string so the same seed always produces the
 * same puzzle (used by the daily puzzle toggle).
 *
 * Both accept a SudokuSpec (default 9x9), so kids 4x4/6x6 and 16x16 mega
 * grids are generated by the same code. Large grids use a node budget while
 * proving uniqueness so generation always terminates quickly.
 */

import { type Grid, rowOf, colOf } from './validator';
import {
  hasUniqueSolution,
  getCandidates,
  findEmptyWithFewestCandidates,
} from './solver';
import { type SudokuSpec, DEFAULT_SPEC, cellsOf } from './spec';

/** Supported difficulty levels, from easiest to hardest. */
export type Difficulty = 'easy' | 'medium' | 'hard' | 'evil';

/** Target number of givens (clues) for each difficulty, per grid size. */
const TARGET_CLUES: Record<number, Record<Difficulty, number>> = {
  4: { easy: 12, medium: 10, hard: 8, evil: 6 },
  6: { easy: 26, medium: 22, hard: 18, evil: 15 },
  9: { easy: 40, medium: 34, hard: 30, evil: 26 },
  16: { easy: 150, medium: 130, hard: 118, evil: 116 },
};

/**
 * Node budget for uniqueness proofs while digging holes. Small grids prove
 * uniqueness in microseconds; 16x16 grids can be slow, so each proof is
 * capped. When the budget is hit the removal is kept back (more givens), so
 * the resulting puzzle is still unique and generation always terminates.
 */
const UNIQUENESS_BUDGETS: Record<number, number> = {
  4: Infinity,
  6: Infinity,
  9: Infinity,
  16: 1_000_000,
};

/** Allowed deviation from the target clue count. */
const CLUE_TOLERANCE = 2;

/**
 * Wider tolerance for large grids: uniqueness proofs near the sparse end of
 * the difficulty curve are slow, so accepting a slightly higher clue count
 * avoids expensive retries while staying within the intended difficulty.
 */
const CLUE_TOLERANCES: Record<number, number> = {
  4: CLUE_TOLERANCE,
  6: CLUE_TOLERANCE,
  9: CLUE_TOLERANCE,
  16: 4,
};

/** Type of a random source: a function returning a float in [0, 1). */
type Random = () => number;

/**
 * Hashes a string into a 32-bit unsigned integer using the xmur3 algorithm.
 */
function hashString(str: string): number {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  h = Math.imul(h ^ (h >>> 16), 2246822507);
  h = Math.imul(h ^ (h >>> 13), 3266489909);
  h ^= h >>> 16;
  return h >>> 0;
}

/**
 * mulberry32: a small, fast deterministic PRNG seeded by a 32-bit integer.
 * Returns a function yielding floats in [0, 1).
 */
function mulberry32(seed: number): Random {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Builds a deterministic PRNG from a seed string (hash then mulberry32). */
function prngFromString(seed: string): Random {
  return mulberry32(hashString(seed));
}

/**
 * Returns a new array with its elements arranged in random order using the
 * Fisher-Yates shuffle driven by the given random source.
 */
function shuffle<T>(items: T[], random: Random): T[] {
  const result = items.slice();
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    const tmp = result[i];
    result[i] = result[j];
    result[j] = tmp;
  }
  return result;
}

/** Counts how many cells hold a non-zero digit in the grid. */
function countClues(grid: Grid): number {
  let count = 0;
  for (const value of grid) {
    if (value !== 0) {
      count++;
    }
  }
  return count;
}

/**
 * Generates a complete, valid solution using randomized backtracking with
 * most-constrained-first cell selection.
 */
function generateFullSolution(random: Random, spec: SudokuSpec): Grid {
  const grid = new Array<number>(cellsOf(spec)).fill(0);
  const search = (): boolean => {
    const index = findEmptyWithFewestCandidates(grid, spec);
    if (index === -2) {
      return false;
    }
    if (index === -1) {
      return true;
    }
    const row = rowOf(index, spec);
    const col = colOf(index, spec);
    for (const digit of shuffle(getCandidates(grid, row, col, spec), random)) {
      grid[index] = digit;
      if (search()) {
        return true;
      }
      grid[index] = 0;
    }
    return false;
  };
  if (!search()) {
    throw new Error('generateFullSolution: failed to fill a complete grid');
  }
  return grid;
}

/**
 * Digs holes into a complete solution by removing cells in random order,
 * keeping every removal that preserves a unique solution, until the target
 * clue count is reached.
 *
 * A single pass suffices: once a removal would create multiple solutions,
 * it can never become safe later, because removing further clues can only add
 * solutions, never restore uniqueness. So failed cells are never retried.
 */
function digHoles(
  solution: Grid,
  targetClues: number,
  random: Random,
  spec: SudokuSpec,
): Grid {
  const puzzle = solution.slice();
  const filled: number[] = [];
  for (let i = 0; i < cellsOf(spec); i++) {
    filled.push(i);
  }
  let clues = cellsOf(spec);
  const budget = UNIQUENESS_BUDGETS[spec.size] ?? Infinity;
  for (const index of shuffle(filled, random)) {
    if (clues <= targetClues) {
      break;
    }
    const value = puzzle[index];
    puzzle[index] = 0;
    if (!hasUniqueSolution(puzzle, spec, budget)) {
      puzzle[index] = value;
    } else {
      clues--;
    }
  }
  return puzzle;
}

/**
 * Generates a sudoku puzzle of the requested difficulty together with its
 * unique solution, using the given random source. The puzzle is guaranteed to
 * have exactly one solution and its clue count is within +/- 2 of the
 * difficulty target for the grid size.
 */
function generate(
  difficulty: Difficulty,
  random: Random,
  spec: SudokuSpec,
): { puzzle: Grid; solution: Grid } {
  const target = TARGET_CLUES[spec.size][difficulty];
  const tolerance = CLUE_TOLERANCES[spec.size] ?? CLUE_TOLERANCE;
  const minClues = target - tolerance;
  const maxClues = target + tolerance;
  const budget = UNIQUENESS_BUDGETS[spec.size] ?? Infinity;
  const maxAttempts = spec.size >= 16 ? 6 : 50;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const solution = generateFullSolution(random, spec);
    const puzzle = digHoles(solution, target, random, spec);
    const clues = countClues(puzzle);
    if (
      clues >= minClues &&
      clues <= maxClues &&
      hasUniqueSolution(puzzle, spec, budget)
    ) {
      return { puzzle, solution };
    }
  }
  throw new Error(`generate: could not generate a '${difficulty}' puzzle`);
}

/**
 * Generates a sudoku puzzle of the requested difficulty together with its
 * unique solution, using Math.random() for a fresh random puzzle on every
 * call. Accepts an optional grid spec (defaults to 9x9).
 */
export function generateSudoku(
  difficulty: Difficulty,
  spec: SudokuSpec = DEFAULT_SPEC,
): { puzzle: Grid; solution: Grid } {
  return generate(difficulty, () => Math.random(), spec);
}

/**
 * Generates a sudoku puzzle deterministically from a seed string together
 * with its unique solution. The same seed, difficulty, and grid size always
 * produce the same puzzle, while different seeds produce different puzzles.
 * Used by the daily puzzle toggle, where the seed is a date string such as
 * "2026-08-08" so every player sees the same puzzle on the same day.
 */
export function generateSudokuSeeded(
  seed: string,
  difficulty: Difficulty,
  spec: SudokuSpec = DEFAULT_SPEC,
): { puzzle: Grid; solution: Grid } {
  return generate(
    difficulty,
    prngFromString(`${seed}:${difficulty}:${spec.size}`),
    spec,
  );
}

/** Convenience export: whether the engine supports the given grid size. */
export function isSupportedSize(size: number): boolean {
  return size in TARGET_CLUES;
}
