/**
 * Sudoku puzzle generator.
 *
 * A valid full solution is generated by randomized backtracking, then cells
 * are removed one by one (in random order, over several passes) while the
 * puzzle keeps a unique solution, until the difficulty's target clue count
 * is reached. Removals that would create multiple solutions are rolled back.
 *
 * Two entry points exist: generateSudoku() uses Math.random() for a fresh
 * random puzzle every call, while generateSudokuSeeded() derives a
 * deterministic PRNG from a seed string so the same seed always produces the
 * same puzzle (used by the daily puzzle page).
 */

import { type Grid, CELLS } from './validator';
import {
  hasUniqueSolution,
  getCandidates,
  findEmptyWithFewestCandidates,
} from './solver';

/** Supported difficulty levels, from easiest to hardest. */
export type Difficulty = 'easy' | 'medium' | 'hard' | 'evil';

/** Target number of givens (clues) for each difficulty. */
const TARGET_CLUES: Record<Difficulty, number> = {
  easy: 40,
  medium: 34,
  hard: 30,
  evil: 26,
};

/** Allowed deviation from the target clue count. */
const CLUE_TOLERANCE = 2;

/** Type of a random source: a function returning a float in [0, 1). */
type Random = () => number;

/**
 * Hashes a string into a 32-bit unsigned integer using the xmur3 algorithm.
 */
function hashString(str: string): number {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  h = Math.imul(h ^ (h >>> 16), 2246822507);
  h = Math.imul(h ^ (h >>> 13), 3266489909);
  h ^= h >>> 16;
  return h >>> 0;
}

/**
 * mulberry32: a small, fast deterministic PRNG seeded by a 32-bit integer.
 * Returns a function yielding floats in [0, 1).
 */
function mulberry32(seed: number): Random {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Builds a deterministic PRNG from a seed string (hash then mulberry32). */
function prngFromString(seed: string): Random {
  return mulberry32(hashString(seed));
}

/**
 * Returns a new array with its elements arranged in random order using the
 * Fisher-Yates shuffle driven by the given random source.
 */
function shuffle<T>(items: T[], random: Random): T[] {
  const result = items.slice();
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    const tmp = result[i];
    result[i] = result[j];
    result[j] = tmp;
  }
  return result;
}

/** Counts how many cells hold a non-zero digit in the grid. */
function countClues(grid: Grid): number {
  let count = 0;
  for (const value of grid) {
    if (value !== 0) {
      count++;
    }
  }
  return count;
}

/**
 * Generates a complete, valid 9x9 solution using randomized backtracking with
 * most-constrained-first cell selection.
 */
function generateFullSolution(random: Random): Grid {
  const grid = new Array<number>(CELLS).fill(0);
  const search = (): boolean => {
    const index = findEmptyWithFewestCandidates(grid);
    if (index === -2) {
      return false;
    }
    if (index === -1) {
      return true;
    }
    const row = Math.floor(index / 9);
    const col = index % 9;
    for (const digit of shuffle(getCandidates(grid, row, col), random)) {
      grid[index] = digit;
      if (search()) {
        return true;
      }
      grid[index] = 0;
    }
    return false;
  };
  if (!search()) {
    throw new Error('generateFullSolution: failed to fill a complete grid');
  }
  return grid;
}

/**
 * Digs holes into a complete solution by removing cells in random order over
 * several passes, keeping every removal that preserves a unique solution.
 * Stops once the target clue count is reached.
 */
function digHoles(solution: Grid, targetClues: number, random: Random): Grid {
  const puzzle = solution.slice();
  const filled: number[] = [];
  for (let i = 0; i < CELLS; i++) {
    filled.push(i);
  }
  outer: for (let pass = 0; pass < 8; pass++) {
    for (const index of shuffle(filled, random)) {
      if (countClues(puzzle) <= targetClues) {
        break outer;
      }
      if (puzzle[index] === 0) {
        continue;
      }
      const value = puzzle[index];
      puzzle[index] = 0;
      if (!hasUniqueSolution(puzzle)) {
        puzzle[index] = value;
      }
    }
  }
  return puzzle;
}

/**
 * Generates a Sudoku puzzle of the requested difficulty together with its
 * unique solution, using the given random source. The puzzle is guaranteed to
 * have exactly one solution and its clue count is within +/- 2 of the
 * difficulty target (easy: 40, medium: 34, hard: 30, evil: 26).
 */
function generate(
  difficulty: Difficulty,
  random: Random,
): { puzzle: Grid; solution: Grid } {
  const target = TARGET_CLUES[difficulty];
  const minClues = target - CLUE_TOLERANCE;
  const maxClues = target + CLUE_TOLERANCE;
  for (let attempt = 0; attempt < 50; attempt++) {
    const solution = generateFullSolution(random);
    const puzzle = digHoles(solution, target, random);
    const clues = countClues(puzzle);
    if (
      clues >= minClues &&
      clues <= maxClues &&
      hasUniqueSolution(puzzle)
    ) {
      return { puzzle, solution };
    }
  }
  throw new Error(`generateSudoku: could not generate a '${difficulty}' puzzle`);
}

/**
 * Generates a Sudoku puzzle of the requested difficulty together with its
 * unique solution, using Math.random() for a fresh random puzzle on every
 * call. The puzzle is guaranteed to have exactly one solution and its clue
 * count is within +/- 2 of the difficulty target (easy: 40, medium: 34,
 * hard: 30, evil: 26).
 */
export function generateSudoku(difficulty: Difficulty): {
  puzzle: Grid;
  solution: Grid;
} {
  return generate(difficulty, () => Math.random());
}

/**
 * Generates a Sudoku puzzle deterministically from a seed string together
 * with its unique solution. The same seed and difficulty always produce the
 * same puzzle, while different seeds produce different puzzles. This is used
 * by the daily puzzle page, where the seed is a date string such as
 * "2026-08-08" so every player sees the same puzzle on the same day.
 */
export function generateSudokuSeeded(
  seed: string,
  difficulty: Difficulty,
): { puzzle: Grid; solution: Grid } {
  return generate(difficulty, prngFromString(`${seed}:${difficulty}`));
}
